const aiTools = [
    {
        id: 1,
        name: "基础创业套餐",
        icon: "🔧",
        category: "engine",
        categoryName: "发动机维修",
        description: "提供三轮车发动机检测、维修和保养服务，包含缸体修复、活塞更换等",
        rating: 4.8,
        users: "5000+",
        price: "paid",
        color: "#fff",
        bgColor: "#667eea",
        dateAdded: "2024-01-15"
    },
    {
        id: 2,
        name: "轮胎专项服务",
        icon: "🛞",
        category: "tire",
        categoryName: "轮胎维修",
        description: "专业轮胎修补、更换、动平衡服务，支持真空胎和普通胎",
        rating: 4.9,
        users: "8000+",
        price: "paid",
        color: "#fff",
        bgColor: "#10b981",
        dateAdded: "2024-01-14"
    },
    {
        id: 3,
        name: "刹车系统维护",
        icon: "�",
        category: "brake",
        categoryName: "刹车系统",
        description: "刹车片更换、刹车油更换、刹车系统调试服务",
        rating: 4.7,
        users: "3500+",
        price: "paid",
        color: "#fff",
        bgColor: "#ec4899",
        dateAdded: "2024-01-13"
    },
    {
        id: 4,
        name: "传动系统修复",
        icon: "⚙️",
        category: "transmission",
        categoryName: "传动系统",
        description: "链条、齿轮、差速器等传动部件的维修和更换",
        rating: 4.6,
        users: "2800+",
        price: "paid",
        color: "#fff",
        bgColor: "#06b6d4",
        dateAdded: "2024-01-12"
    },
    {
        id: 5,
        name: "定期保养套餐",
        icon: "🔩",
        category: "maintenance",
        categoryName: "定期保养",
        description: "三轮车全面检查和保养服务，包含机油更换、滤芯更换等",
        rating: 4.8,
        users: "6200+",
        price: "paid",
        color: "#fff",
        bgColor: "#84cc16",
        dateAdded: "2024-01-11"
    },
    {
        id: 6,
        name: "配件销售中心",
        icon: "�",
        category: "accessories",
        categoryName: "配件销售",
        description: "原厂配件和优质副厂配件销售，支持安装服务",
        rating: 4.5,
        users: "1.2万",
        price: "paid",
        color: "#fff",
        bgColor: "#f97316",
        dateAdded: "2024-01-10"
    },
    {
        id: 7,
        name: "电池检测服务",
        icon: "�",
        category: "engine",
        categoryName: "发动机维修",
        description: "电池容量检测、修复和更换服务，支持铅酸和锂电池",
        rating: 4.7,
        users: "4500+",
        price: "paid",
        color: "#fff",
        bgColor: "#667eea",
        dateAdded: "2024-01-09"
    },
    {
        id: 8,
        name: "上门维修服务",
        icon: "�",
        category: "tire",
        categoryName: "轮胎维修",
        description: "专业师傅上门维修，24小时响应，快速解决问题",
        rating: 4.9,
        users: "9000+",
        price: "paid",
        color: "#fff",
        bgColor: "#10b981",
        dateAdded: "2024-01-08"
    },
    {
        id: 9,
        name: "故障诊断服务",
        icon: "🔍",
        category: "brake",
        categoryName: "刹车系统",
        description: "专业故障诊断，快速定位问题，提供维修方案",
        rating: 4.6,
        users: "3200+",
        price: "free",
        color: "#fff",
        bgColor: "#ec4899",
        dateAdded: "2024-01-07"
    },
    {
        id: 10,
        name: "整车清洗服务",
        icon: "🧼",
        category: "transmission",
        categoryName: "传动系统",
        description: "整车深度清洗，包括发动机舱、底盘等部位",
        rating: 4.5,
        users: "2100+",
        price: "paid",
        color: "#fff",
        bgColor: "#06b6d4",
        dateAdded: "2024-01-06"
    },
    {
        id: 11,
        name: "改装升级服务",
        icon: "⚡",
        category: "maintenance",
        categoryName: "定期保养",
        description: "动力升级、外观改装、性能优化等定制服务",
        rating: 4.8,
        users: "1800+",
        price: "paid",
        color: "#fff",
        bgColor: "#84cc16",
        dateAdded: "2024-01-05"
    },
    {
        id: 12,
        name: "保险代办服务",
        icon: "�",
        category: "accessories",
        categoryName: "配件销售",
        description: "代办三轮车保险、年检等业务，省时省心",
        rating: 4.4,
        users: "1500+",
        price: "paid",
        color: "#fff",
        bgColor: "#f97316",
        dateAdded: "2024-01-04"
    },
    {
        id: 13,
        name: "道路救援服务",
        icon: "🚒",
        category: "engine",
        categoryName: "发动机维修",
        description: "24小时道路救援，拖车服务，紧急维修",
        rating: 4.9,
        users: "5600+",
        price: "paid",
        color: "#fff",
        bgColor: "#667eea",
        dateAdded: "2024-01-03"
    },
    {
        id: 14,
        name: "充电设备安装",
        icon: "�",
        category: "tire",
        categoryName: "轮胎维修",
        description: "家用充电桩安装、维护和调试服务",
        rating: 4.6,
        users: "1200+",
        price: "paid",
        color: "#fff",
        bgColor: "#10b981",
        dateAdded: "2024-01-02"
    },
    {
        id: 15,
        name: "技术咨询服务",
        icon: "�",
        category: "brake",
        categoryName: "刹车系统",
        description: "专业技术咨询，解答维修保养疑问",
        rating: 4.7,
        users: "2800+",
        price: "free",
        color: "#fff",
        bgColor: "#ec4899",
        dateAdded: "2024-01-01"
    },
    {
        id: 16,
        name: "二手车评估",
        icon: "�",
        category: "transmission",
        categoryName: "传动系统",
        description: "专业二手车评估服务，公平公正",
        rating: 4.5,
        users: "900+",
        price: "paid",
        color: "#fff",
        bgColor: "#06b6d4",
        dateAdded: "2023-12-31"
    },
    {
        id: 17,
        name: "学徒培训计划",
        icon: "🎓",
        category: "maintenance",
        categoryName: "定期保养",
        description: "专业维修技术培训，包教包会",
        rating: 4.6,
        users: "600+",
        price: "paid",
        color: "#fff",
        bgColor: "#84cc16",
        dateAdded: "2023-12-30"
    },
    {
        id: 18,
        name: "会员专属服务",
        icon: "�",
        category: "accessories",
        categoryName: "配件销售",
        description: "会员专享折扣、优先服务、免费检测等权益",
        rating: 4.9,
        users: "3500+",
        price: "paid",
        color: "#fff",
        bgColor: "#f97316",
        dateAdded: "2023-12-29"
    }
];

const categoryColors = {
    "engine": "#667eea",
    "tire": "#10b981",
    "brake": "#ec4899",
    "transmission": "#06b6d4",
    "maintenance": "#84cc16",
    "accessories": "#f97316"
};